config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/ra_messages/index(/:id)' => 'claims#find', constraints: { query_string: /findstr/ }
  get 'ra_messages/index'
  
  get '/forms/index(/:id)' => 'forms#find', constraints: { query_string: /findstr/ }
  get '/forms/index'

  get '/claims/index(/:id)' => 'claims#find', constraints: { query_string: /findstr/ }
  get '/claims/index' 
  get '/daily_charts/index' => 'daily_charts#find', constraints: { query_string: /findstr/ }
  get '/daily_charts/index'
  get '/drugs/index' => 'drugs#find', constraints: { query_string: /findstr/ }
  get '/drugs/index' 
  get '/providers/index' => 'providers#find', constraints: { query_string: /findstr/ }
  get '/providers/index' 
  get '/reports/index' => 'reports#find', constraints: { query_string: /findstr/ }
  get '/reports/index' 
  get '/procedures/index' => 'procedures#find', constraints: { query_string: /findstr/ }
  get '/procedures/index' 
  get '/diagnoses/index' => 'diagnoses#find', constraints: { query_string: /findstr/ }
  get '/diagnoses/index' 
  get '/doctors/index' => 'doctors#find', constraints: { query_string: /findstr/ }
  get '/doctors/index' 
 # post '/daysheet/index', to: 'sessions#set_doctor' 
  post '/set_doctor', to: 'sessions#set_doctor'
  get '/set_doctor', to: 'sessions#set_doctor' 
  get '/daysheet/index', to: 'daysheet#index', as: :daysheet
  get '/vaccines/index', to:  "vaccines#find", constraints: { query_string: /findstr/ }
  get '/vaccines/index' 
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/news', to: 'static_pages#news'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/patients(/:id)', to: 'patients#find', constraints: { query_string: /findstr/ }
  post  '/patients(/:id)/card', to: 'patients#card'
  get '/patients(/:id)/card', to: 'patients#card'
  #get '/daysheet/card', to: 'patients#card'
  #post  '/daysheet/card', to: 'patients#card'

  get  '/patsignup', to: 'patients#new'
  post '/patsignup', to: 'patients#create'

  get '/visits' => 'visits#daysheet', constraints: { query_string: /date/ }
  get '/visits' => 'visits#index'
  get '/billings' => 'billings#index'
  post '/billings/export_csv', to: 'billings#export_csv'
  post '/billings/export_edt', to: 'billings#export_edt'
  post '/billings/export_cabmd', to: 'billings#export_cabmd'
  get "/procedures/get_by_code", to: "procedures#get_by_code" 
  
  
  resources :users
  resources :patients do
    get 'label', on: :member
    get 'addrlabel', on: :member
    get 'chart', on: :member
    resources :invoices do
      get 'invoice', on: :member
    end
    resources :visits do  # , shallow: true         #, only: [:show, :create, :destroy, :new, :index]
      get 'visitform', on: :member
      get 'receipt', on: :member
      get 'referralform', on: :member
      get 'sendclaim', on: :member
      resources :documents
    end
  end
  
  resources :ra_messages, :ra_accounts, :ra_errcodes, :doctors, :diagnoses, :procedures, :providers, 
	    :drugs, :invoices, :vaccines, :daily_charts, :export_files, :edt_files, :forms

  resources :claims do
    resources :services
  end
  resources :reports do
     get 'export', on: :member
     get 'download', on: :member
  end
  resources :paystubs do
     get 'export', on: :member
     get 'download', on: :member
  end
  get 'budget', to: 'paystubs#budget'

# resources :billings     # historical billing table - not used
  
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  include My::Forms

	before_action :logged_in_user #, only: [:create, :destroy, :index]
#        before_action :current_doctor_set #, only: [:create, :visitform, :receipt]  
#	before_action :admin_user, only: :destroy

  def index (defdate = Date.today )
    date = params[:date] || defdate
    @patient = Patient.find(params[:patient_id])
    if @patient.visits.any?
	   @visits = @patient.visits.paginate(page: params[:page])
	   render 'index'
      else
	   flash.now[:warning] = "No visits found for date: #{date.inspect}" 
	   render  inline: '', layout: true
    end
  end

  def new
        @patient = Patient.find(params[:patient_id])
	@visit = @patient.visits.where('date(entry_ts)=?', Date.today)
	if @visit.present?
	  flash[:warning] = "Only 1 visit is allowed per patient per day"
          redirect_to @patient
	else
           @visit = @patient.visits.new
           @visit.entry_ts = Time.now #.strftime("%Y-%m-%d at %H:%M")
	   @visit.doc_id ||= current_doctor.id rescue nil
	   if @visit.save
	      redirect_to @patient
           else 
     	      flash.now[:danger] = 'Error saving new visit'		   
	      render 'new'
	   end
	end
  end

  def create
    @patient = Patient.find(params[:patient_id])
    @visit = @patient.visits.build(visit_params)
    @visit.entry_by = current_user.name
    @visit.entry_ts = Time.now unless (@visit.entry_ts.present? && @visit.entry_ts < Date.tomorrow)

    set_visit_fees ( @visit )

    if @visit.save
      @patient.update_attribute(:last_visit_date, @visit.entry_ts)

      doc = @visit.documents.create(:document => params[:visit][:document]) if params[:visit][:document].present?
      if doc.blank? || doc.errors.blank?
        flash[:success] = "Visit saved #{params[:entry_ts]} "
        redirect_to @patient
      else
        flash.now[:danger] =  doc.errors.full_messages.first rescue ''
        render 'new'
      end
    else 
        render 'new'
    end
  end

  def edit
     @visit = Visit.find(params[:id])
  end

  def update
    @visit = Visit.find(params[:id])
    @patient = Patient.find(@visit.patient_id)

    doc = @visit.documents.create(:document => params[:visit][:document]) if params[:visit][:document].present?
    if @visit.update_attributes(visit_params)
      @patient.update_attribute(:last_visit_date, @visit.created_at)
      
#      if current_doctor.blank? || @visit.doc_id != current_doctor.id
#	 set_doc_session ( @visit.doc_id )
#	 flash.now[:info] = "Current Doctor set to: Dr. #{@visit.doctor.lname}" if @visit.doctor.lname
#      end

      set_visit_fees( @visit )
      @visit.save
      flash[:success] = "Visit updated"
      redirect_to daysheet_path
    else
	    flash.now[:danger] =  doc.errors.full_messages.first rescue ''
      render 'edit'
    end
  end

  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy
    flash[:success] = "Visit deleted"
    redirect_back(fallback_location: daysheet_path)
  end

  def show
     @visit = Visit.find(params[:id])
  end

   def sendclaim
       require 'net/http'
       require 'uri'

       @visit = Visit.find(params[:id])
       @patient = Patient.find(@visit.patient_id)
       @patient.fname = @patient.full_sex unless @patient.fname.present?
       @doctor = Doctor.find(@visit.doc_id)
       @xml = render_to_string "show.xml"

       uri = URI.parse(CABMDURL)
       http= Net::HTTP.new(uri.host,uri.port)
       http.use_ssl = true
       
       req = Net::HTTP::Post.new(uri.request_uri, {'Content-Type' => 'application/xml'})
       req.body = @xml

       res = http.request(req)
       @xmlhash = JSON.parse(res.body)
# {"success"=>true, "errors"=>[], "messages"=>[], "reference_id"=>"332933", "accounting_number"=>"0004MZ4Z"}
       
       if @xmlhash['success'] 
	  acc_num = @xmlhash['accounting_number']
          flash[:success] = "Claim #{acc_num} sent to cab.md " 
          @visit.update_attribute(:status, BILLED)
          @visit.update_attribute(:billing_ref, acc_num)
       else
	  errors = @xmlhash['errors']
	  messages = @xmlhash['messages']
	  flash[:danger] = "Error sending claim : #{@xmlhash}"
          @visit.update_attribute(:status, READY)
	  @visit.update_attribute(:billing_ref, errors.join(',')) if errors.present?
       end

       respond_to(:html)
       redirect_to patient_visit_path
  end

  def daysheet (defdate = Date.today)
      date = params[:date] || defdate
      flash.alert = 'Daysheet for ' + date
      @visits = Visit.where("date(created_at) = ?", date)  
      if @visits.any?
	   @visits = @visits.paginate(page: params[:page])
	   render 'index'
      else
	      flash.now[:warning] = "No visits found for date: #{date.inspect}" 
#           redirect_to visits_url
	    render "no_daysheet_found"
      end
  end

# Generate visit form in PDF
  def visitform
        @visit = Visit.find(params[:id])
	@patient = Patient.find(@visit.patient_id)
        @pdf = build_visit_form( @patient, @visit )

        respond_to do |format|
          format.html do
            send_data @pdf.render,
            filename: "form_#{@patient.full_name}",
            type: 'application/pdf',
            disposition: 'inline'
          end
	  format.js { @pdf.render_file File.join(Rails.root, 'public', 'uploads', "visitform.pdf") }
	end
  end  

# Generate PDF receipt for 3RD party services  
  def receipt
        @visit = Visit.find(params[:id])
	@patient = Patient.find(@visit.patient_id)
        @pdf = build_visit_receipt( @patient, @visit )

        respond_to do |format|
          format.html do
          send_data @pdf.render,
            filename: "receipt_#{@patient.full_name}",
            type: 'application/pdf',
            disposition: 'inline'
	  end
	  format.js { @pdf.render_file File.join(Rails.root, 'public', 'uploads', "receipt.pdf") }
	end
  end

# Generate referral form for this visit
  def referralform
	@visit = Visit.find(params[:id])
        @patient = Patient.find(@visit.patient_id)
	@pdf = build_referral_form( @patient, @visit )
        
        respond_to do |format|
          format.html do
	    send_data @pdf.render,
              filename: "referral_#{@patient.full_name}",
              type: 'application/pdf',
              disposition: 'inline'
	  end
	  format.js { @pdf.render_file File.join(Rails.root, 'public', 'uploads', "referralform.pdf") }
	end
  end

  private

    def visit_params
      params.require(:visit).permit(:vis_type, :diag_code, :patient_id, :doc_id, #:services,
				    :proc_code, :proc_code2, :proc_code3, :proc_code4,
				    :units, :units2, :units3, :units4, 
				    :fee, :fee2, :fee3, :fee4,
				    :bil_type, :bil_type2, :bil_type3, :bil_type4, 
				    :reason, :notes, :entry_ts, :status, :duration, 
				    :entry_by, :provider_id, :temp, :bp, :pulse, :weight, :export_file, :billing_ref, :document )
    end      

    def set_visit_fees ( visit )
      visit.fee = visit.fee2 = visit.fee3 = visit.fee4 = 0.0
      if !visit.proc_code.blank? 
	      p = Procedure.find_by(code: visit.proc_code) 
	      visit.fee = p.cost*visit.units rescue 0
      end
      if !visit.proc_code2.blank? 
	      p2 = Procedure.find_by(code: visit.proc_code2) 
	      visit.fee2 = p2.cost*visit.units2 rescue 0
      end  
      if !visit.proc_code3.blank? 
	      p3 = Procedure.find_by(code: visit.proc_code3) 
	      visit.fee3 = p3.cost*visit.units3 rescue 0
      end  
      if !visit.proc_code4.blank? 
	      p4 = Procedure.find_by(code: visit.proc_code4) 
	      visit.fee4 = p4.cost*visit.units4 rescue 0
      end  
    end

end

app/helpers/visits_helper.rb
module VisitsHelper

end

app/views/visits/_edit.html.erb
<%
   provide(:title, 'Edit Visit')
   provide(:button_text, 'Save changes')
   @patient = Patient.find(@visit.patient_id)
%>
 
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">&times;</button>
	<b class="modal-title" id="myModalLabel"><%= @patient.full_name %>: Visit of <%= @visit.entry_ts %></b>
</div>
<div class="modal-body">
       <%= render 'form' %>
</div>

app/views/visits/_form.html.erb
<%= form_for [@patient, @visit],  :html => {:multipart => true} do |f| %> 
  <%= render 'shared/error_messages', object: f.object %>

<% 
   doc_id = @visit.doctor.id || (current_doctor.id if current_doctor) 
   @procedures = get_active_procedures 
   @insured = [HCP_PATIENT,RMB_PATIENT,WCB_PATIENT].include?(@patient.pat_type) 

  if current_user.admin? 
     disabled = []
  elsif @visit.status == ERROR 
     disabled = ( READY..CANCELLED ).to_a
  elsif @visit.billing_ref.present?
     disabled = [ARRIVED,READY,CANCELLED]
  elsif @visit.hcp_proc_codes.present? 
    if @insured
       disabled = [BILLED,PAID]
    else
       disabled = [READY]
    end
  elsif @visit.proc_codes.empty?
     disabled = [READY,BILLED,PAID] 
  elsif @visit.cash?
     disabled = [READY,BILLED]
  else 
     disabled = []
  end 
%>

  <!-- Row 0 if new visit or admin --> 

     <div class="row">
     <% if action_name == 'new' %>
	<div class="col-sm-4">
	   <%= f.label "Visit Date/time" %>
	   <%= f.datetime_field :entry_ts, datetime_separator: ' at ' %>
  	</div>
     <% elsif current_user.admin? && action_name == 'edit' %>
   	<div class="col-sm-6">
  	  <%= f.label "Billing Reference" %>
 	  <%= f.text_field :billing_ref %>
  	</div>
    <% end %>
    </div>

  <!-- Row 1 --> 

<div class="row">
  <div class="col-sm-4">
  <%= f.label "Doctor" %>
  <%= f.collection_select(:doc_id, get_active_doctors, :id, :lname, prompt: 'Select', selected: doc_id) %>
  </div>

  <div class="col-sm-2">
  <%= f.label "Service" %>
  <%= f.collection_select :proc_code, @procedures, :code, :code, prompt: 'Select', include_blank: 'None' %> <!--#, selected: @visit.proc_code || 'A007A'  -->
  <!--  f.hidden_field(:fee, id: :fee) -->
  </div>

  <div class="col-sm-2">
  <%= f.label "Service" %>
  <%= f.collection_select :proc_code2, @procedures, :code, :code, prompt: 'Select', include_blank: 'None'  %>
  </div>

  <div class="col-sm-2">
  <%= f.label "Service" %>
  <%= f.collection_select :proc_code3, @procedures, :code, :code, prompt: 'Select', include_blank: 'None'  %>
  </div>

  <div class="col-sm-2">
  <%= f.label "Service" %>
  <%= f.collection_select :proc_code4, @procedures, :code, :code, prompt: 'Select', include_blank: 'None'  %>
  </div>
</div

  <!-- Row 2 -->

<div class="row">
  <div class="col-sm-4">
  <%= f.label "Diagnosis" %>
  <%=  f.collection_select :diag_code, get_active_diagnoses, :code, :descr_with_code, prompt: 'Select' %> <!--  #, selected: @visit.diag_code || '460.000' -->
  </div>

  <div class="col-sm-2">
  <%= f.label :units %>
  <%= f.select :units, UNITS, prompt:  'Select' %>
  </div>

  <div class="col-sm-2">
  <%= f.label :units %>
  <%= f.select :units2, UNITS, prompt: 'Select' %>
  </div>

  <div class="col-sm-2">
  <%= f.label :units %>
  <%= f.select :units3, UNITS, prompt: 'Select' %>
  </div>

  <div class="col-sm-2">
  <%= f.label :units %>
  <%= f.select :units4, UNITS, prompt: 'Select' %>
  </div>
</div>

  <!-- Row 3 -->

<div class="row">
  <div class="col-sm-2">
  <%= f.label "Duration" %>
  <%= f.select :duration, DURATIONS, default: 10  %>
  </div>
  <div class="col-sm-2 ">
  <%= f.label "Visit Type" %>
  <%= f.select :vis_type, VISIT_TYPES, placeholder: 'Visit type', default: 'WS' %>
  </div>
  
  <div class="col-sm-2">
  <%= f.label "Bill Type" %>
  <div id="my_bil_type"> <%= @visit.bil_type_str %></div>
  <%= f.hidden_field :bil_type %>
  </div>

  <div class="col-sm-2">
  <%= f.label "Bill Type" %>
  <div id="my_bil_type2"> <%= @visit.bil_type2_str %></div>
  <%= f.hidden_field :bil_type2  %>
  </div>

  <div class="col-sm-2">
  <%= f.label "Bill Type" %>
  <div id="my_bil_type3"> <%= @visit.bil_type3_str %></div>
  <%= f.hidden_field :bil_type3  %>
  </div>

  <div class="col-sm-2">
  <%= f.label "Bill Type" %>
  <div id="my_bil_type4"> <%= @visit.bil_type4_str %></div>
  <%= f.hidden_field :bil_type4  %>
  </div>
</div>

  <!-- Row 4 -->

<div class="row">
  <div class="col-sm-4" id="visit_statuses">
  <%= f.label "Visit Status" %>
  <%= f.select :status, VISIT_STATUSES, placeholder: 'Status', disabled: disabled %>
  </div>

  <div class="col-sm-2">
  <%= f.label :Temperature %>
  <%= f.text_field :temp %>
  </div>
  <div class="col-sm-2">
  <%= f.label 'Heart Rate' %>
  <%= f.text_field :pulse %>
  </div>
  <div class="col-sm-2">
  <%= f.label "BP (H/L)" %>
  <%= f.text_field :bp %>
  </div>
  <div class="col-sm-2">
  <%= f.label "Weight" %>
  <%= f.text_field :weight %>
  </div>
</div>

  <!-- Row 5: Reason for visit  -->

<div class="row">
  <div class="col-sm-12">
  <%= f.label "Reason for visit" %>
  <%= f.text_area :reason, rows: 2, placeholder: 'Reason for visit' %>
  </div>
</div>

<!-- Row 6: upload docs -->
<div class="row">
  <div class="col-sm-12"> 
    <%= f.label :'PDF documents' %>
      <% @visit.documents.each do |d| %>
      <% next unless d.document.file.present? %>
      <%= link_to d.document.file.filename, d.document.url.to_s %>
      <% end %>
    <%= f.file_field :document %>
  </div>
</div>

<!-- Row 7: Notes, submit button -->
<div class="row">
  <div class="col-sm-12"> 
  <%= f.text_area :notes, rows:4, placeholder: 'Notes' %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <p>
  </div>
</div>

</div>
<% end %>

<script>
$(document).ready(function() {
//    $.fn.select2.defaults.set( "theme", "classic" );
    $( "#visit_diag_code" ).select2();
    $('#visit_proc_code').select2();
    $('#visit_proc_code2').select2();
    $('#visit_proc_code3').select2();
    $('#visit_proc_code4').select2();

    var proccode = $('#new_visit select[name="visit[proc_code]"]');

    (proccode.val() =='') ? $('#visit_statuses').hide() : $('#visit_statuses').show();
    proccode.change(function () {
      (proccode.val() =='') ? $('#visit_statuses').hide() : $('#visit_statuses').show();
    });

});

// Select proper bill type for the procedure
var pc = document.getElementById("visit_proc_code");
$(pc).change(function () {
  if ($(this).val()) {
    get_bil_type( $(this).val() , '');
  } else {
    var bt = document.getElementById('visit_bil_type');
    $(bt).val(null);
    var v = document.getElementById('my_bil_type');
    v.innerHTML = '';
  }
});

var pc2 = document.getElementById("visit_proc_code2");
$(pc2).change(function () {
  if ($(this).val()) {
     get_bil_type( $(this).val() , '2' );
  } else {
    var bt2 = document.getElementById('visit_bil_type2');
    $(bt2).val(null);
    var v2 = document.getElementById('my_bil_type2');	  
    v2.innerHTML = '';
  }
});

var pc3 = document.getElementById("visit_proc_code3");
$(pc3).change(function () {
  if ($(this).val()) {
     get_bil_type( $(this).val() , '3' );
  } else {
    var bt3 = document.getElementById('visit_bil_type3');
    $(bt3).val(null);
    var v3 = document.getElementById('my_bil_type3');	  
    v3.innerHTML = '';
  }
});

var pc4 = document.getElementById("visit_proc_code4");
$(pc4).change(function () {
  if ($(this).val()) {
    get_bil_type( $(this).val() , '4' );
  } else {
    var bt4 = document.getElementById('visit_bil_type4');
    $(bt4).val(null);
    var v4 = document.getElementById('my_bil_type4');	  
    v4.innerHTML = '';
  }
});

function get_bil_type ( code, suff ) {
	var request = "/procedures/get_by_code?code=" + code;
	var aj = $.ajax({
        url: request,
        type: 'get',
        data: $(this).serialize()
    }).done(function (data) {
	select_statuses(data, suff);
        set_btype(data, suff);
    }).fail(function (data) {
        console.log('AJAX request has FAILED');
    });
}

function set_btype( proc, suff ) {
  var v = document.getElementById('visit_bil_type'+suff);
  var v2 = document.getElementById('my_bil_type'+suff);
  if ( proc.ptype == '1') {
	var btype = <%= BILLING_TYPES[@visit.pat_btype] %>; 	
        $(v).val(btype);
	var btype_str = <%= @visit.pat_btype.to_s.inspect.html_safe %> || 'HCP';
	v2.innerHTML = btype_str;
  } else if ( proc.ptype == '2') {
	$(v).val('4');
	v2.innerHTML = 'CSH';
  } else {
        $(v).val(null);
	v2.innerHTML = '';
  }
}

function select_statuses( proc, suff ) {
  var v = document.getElementById('visit_statuses').getElementsByTagName("option");
  var insured = <%= @insured %>;
  if (proc.ptype == '2' && suff.length === 0  || !insured) {
        v[1].disabled = true;  // READY
        v[2].disabled = false;
        v[3].disabled = false;
     }else{
        v[1].disabled = false;
        v[2].disabled = true;
        v[3].disabled = true;
     }
}

</script>

app/views/visits/_receipt.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">&times;</button>
	<b class="modal-title" id="myModalLabel"><%= @patient.full_name %>  - Cash Receipt</b>
</div>
<div class="modal-body">
  <embed src="/uploads/receipt.pdf" frameborder="0" width="100%" height="600px">
</div>
<div class="modal-footer">
  <button class="btn btn-primary" class="close" data-dismiss="modal">Dismiss</button>
</div>

app/views/visits/_visit.html.erb
<tr>
  <td><%= link_to visit.entry_ts, patient_visit_path(@patient,visit) %> </td>
  <td>
  <% if remote %>
     <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_patient_visit_path(@patient,visit), remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %> </td>
  <% else %>
     <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_patient_visit_path(@patient,visit) %>
  <% end %>
  </td>
  <td><%= visit.doctor.lname %></td>
  <td><%= visit.diag_scode %></td>
  <td><%= visit.proc_codes %></td>
  <td><%= visit.status_str %></td>
</tr>

app/views/visits/show.html.erb
<%   
  @patient = Patient.find(@visit.patient_id) 
  @doctor = Doctor.find(@visit.doc_id)
  provide(:title, "#{@patient.full_name} : #{@visit.entry_ts}") 
%>
<%= render "shared/modal", size: 'lg' %>

<h1> <%= @patient.full_name %> : Visit of <%= time_tag(@visit.entry_ts) %>  </h1>

<% diag = Diagnosis.find_by(code: @visit.diag_code) %>
<% codes = [@visit.proc_code, @visit.proc_code2, @visit.proc_code3, @visit.proc_code4] %>

<div class="form-group col-sm-10 col-md-10 col-sm-offset-1 col-md-offset-1">
<div class="row">
	
<section>
<pre class="pre-scrollable-large">
<b>Doctor</b> :    <%= @visit.doctor.lname %>
<b>Reason for Visit </b>: <%= @visit.reason %>
<b>Diagnosis</b> : <%= @visit.diag_code %> : <%= diag.descr rescue '' %>
<b>Procedure(s)</b> : <%=  @visit.proc_codes %>
<b>Billing Type(s) </b>: <%= @visit.bil_type_str %>, <%= @visit.bil_type2_str %>, <%= @visit.bil_type3_str %>, <%= @visit.bil_type4_str %>
<b>Units </b>: <%= @visit.all_units.join',' %>
<b>Billed amount: <%= sprintf '$%.2f',@visit.total_fee %> Insured services: </b><%= sprintf '$%.2f',@visit.total_insured_fees %> <b>Other services:</b> <%= sprintf '$%.2f',@visit.total_non_insured_fees %>
<b>Vital signs</b>: T: <%= @visit.temp %> P: <%= @visit.pulse %> BP: <%= @visit.bp %>
<b>Duration </b>: <%= @visit.duration %> minutes
<b>Status </b>: <%= @visit.status_str %> 
<b>Entry by </b>: <%= @visit.entry_by %>
<b>Entered at </b>: <%= @visit.entry_ts %>
<% if @visit.billing_ref.present? %>
<b>Billing Ref# </b>: <%= @visit.billing_ref %>
<% end %>
<% if @visit.export_file.present? %>
<b>Export file</b>: <%= @visit.export_file %>
<% end %>
<% if @visit.amount.present? %>
<b>Amount Paid </b>: <%= sprintf '$%.2f', @visit.amount %>
<% end %>
<% if @visit.documents.present? %>
<b>Documents</b>: 
<% @visit.documents.each do |d| %>
   <% next unless d.document.file.present? %>
   <%= link_to d.document.file.filename, d.document.url.to_s %>
<% end %>
<% end %>

</pre>

<% if @visit.notes.present? %>
<div class="panel panel-info">
   <div class="visit-notes-panel-body">
<b>Notes </b>: <%= @visit.notes.html_safe %>	     
   </div>
</div>
<% end %>

</section>
</div>

<p>
<% remote = device_is_desktop? %>

<div class="row">
 <% if @visit.status < BILLED || current_user.admin? %>
 <div class="col-sm-3 col-md-2">
  <%= button_to "Edit Visit", edit_patient_visit_path(@patient), remote: remote, 'data-toggle':  "modal", 'data-target': '#modal-window', class: "btn btn-primary clickable", method: "get" %>
 </div>
 <% end %>

<div class="col-sm-3 col-md-2">
<%= button_to "Visit Form", visitform_patient_visit_path(@patient), remote: remote, 'data-toggle':  "modal", 'data-target': '#modal-window',  class:"btn btn-primary clickable", method: 'get'  %>
</div>

<div class="col-sm-3 col-md-2">
<%= button_to "Referral Form", referralform_patient_visit_path(@patient), remote: remote, 'data-toggle':  "modal", 'data-target': '#modal-window',class: "btn btn-primary clickable", method: 'get' %>
</div>

 <% if @visit.cash? %> 
 <div class="col-sm-3 col-md-2">
 <%= button_to "Receipt", receipt_patient_visit_path(@patient), remote: remote, 'data-toggle':  "modal", 'data-target': '#modal-window', class: "btn btn-primary clickable", method: 'get' %>
 </div>
 <% end %>
 
 <% if @visit.ready_to_bill? %>
 <div class="col-sm-3 col-md-2">
 <%= button_to "Send to Cab.md", sendclaim_patient_visit_path(@patient), class: "btn btn-primary", method: 'get'  %>
 </div>
 <% end %>

 <div class="col-sm-3 col-md-2">
 <%= button_to "Back To Patient", patient_path(@patient), class: "btn btn-primary", method: 'get'  %>
 </div>

</div>
</div>