config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/ra_messages/index(/:id)' => 'claims#find', constraints: { query_string: /findstr/ }
  get 'ra_messages/index'
  
  get '/forms/index(/:id)' => 'forms#find', constraints: { query_string: /findstr/ }
  get '/forms/index'

  get '/claims/index(/:id)' => 'claims#find', constraints: { query_string: /findstr/ }
  get '/claims/index' 
  get '/daily_charts/index' => 'daily_charts#find', constraints: { query_string: /findstr/ }
  get '/daily_charts/index'
  get '/drugs/index' => 'drugs#find', constraints: { query_string: /findstr/ }
  get '/drugs/index' 
  get '/providers/index' => 'providers#find', constraints: { query_string: /findstr/ }
  get '/providers/index' 
  get '/reports/index' => 'reports#find', constraints: { query_string: /findstr/ }
  get '/reports/index' 
  get '/procedures/index' => 'procedures#find', constraints: { query_string: /findstr/ }
  get '/procedures/index' 
  get '/diagnoses/index' => 'diagnoses#find', constraints: { query_string: /findstr/ }
  get '/diagnoses/index' 
  get '/doctors/index' => 'doctors#find', constraints: { query_string: /findstr/ }
  get '/doctors/index' 
 # post '/daysheet/index', to: 'sessions#set_doctor' 
  post '/set_doctor', to: 'sessions#set_doctor'
  get '/set_doctor', to: 'sessions#set_doctor' 
  get '/daysheet/index', to: 'daysheet#index', as: :daysheet
  get '/vaccines/index', to:  "vaccines#find", constraints: { query_string: /findstr/ }
  get '/vaccines/index' 
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/news', to: 'static_pages#news'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/patients(/:id)', to: 'patients#find', constraints: { query_string: /findstr/ }
  post  '/patients(/:id)/card', to: 'patients#card'
  get '/patients(/:id)/card', to: 'patients#card'
  #get '/daysheet/card', to: 'patients#card'
  #post  '/daysheet/card', to: 'patients#card'

  get  '/patsignup', to: 'patients#new'
  post '/patsignup', to: 'patients#create'

  get '/visits' => 'visits#daysheet', constraints: { query_string: /date/ }
  get '/visits' => 'visits#index'
  get '/billings' => 'billings#index'
  post '/billings/export_csv', to: 'billings#export_csv'
  post '/billings/export_edt', to: 'billings#export_edt'
  post '/billings/export_cabmd', to: 'billings#export_cabmd'
  get "/procedures/get_by_code", to: "procedures#get_by_code" 
  
  
  resources :users
  resources :patients do
    get 'label', on: :member
    get 'addrlabel', on: :member
    get 'chart', on: :member
    resources :invoices do
      get 'invoice', on: :member
    end
    resources :visits do  # , shallow: true         #, only: [:show, :create, :destroy, :new, :index]
      get 'visitform', on: :member
      get 'receipt', on: :member
      get 'referralform', on: :member
      get 'sendclaim', on: :member
      resources :documents
    end
  end
  
  resources :ra_messages, :ra_accounts, :ra_errcodes, :doctors, :diagnoses, :procedures, :providers, 
	    :drugs, :invoices, :vaccines, :daily_charts, :export_files, :edt_files, :forms

  resources :claims do
    resources :services
  end
  resources :reports do
     get 'export', on: :member
     get 'download', on: :member
  end
  resources :paystubs do
     get 'export', on: :member
     get 'download', on: :member
  end
  get 'budget', to: 'paystubs#budget'

# resources :billings     # historical billing table - not used
  
end

app/models/vaccine.rb
class Vaccine < ApplicationRecord

	default_scope -> { order(name: :asc) }

	before_validation { name.strip! rescue '' }
	before_validation { target.strip! rescue '' }

	validates :name, uniqueness: true, presence:true
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController
	before_action :logged_in_user #, only: [:index, :edit, :update]
        before_action :admin_user,   only: :destroy

  def index
      @vaccines = Vaccine.paginate(page: params[:page], per_page: $per_page)
      flash.now[:info] = "Showing All Vaccines"
  end

  def find
      str = params[:findstr].strip
      @vaccines = myfind(str)
      if @vaccines.any?
         @vaccines = @vaccines.paginate(page: params[:page])
         flash.now[:info] = "Found #{@vaccines.count} #{'vaccine'.pluralize(@vaccines.count)} matching string #{str.inspect}"
         render 'index'
      else
         @vaccines = Vaccine.paginate(page: params[:page])
         @vaccines = Vaccine.new
         flash.now[:warning] = "Vaccine  #{str.inspect} was not found"
         render  inline: '', layout: true
      end
  end

  def show
    if Vaccine.exists?(params[:id])
       @vaccine = Vaccine.find(params[:id])
    else
       redirect_to vaccines_path
    end
  end

  def new
    @vaccine = Vaccine.new
  end

  def create
    @vaccine = Vaccine.new(vaccine_params)
    if @vaccine.save
       flash[:success] = "Vaccine added "
       redirect_to @vaccine
    else
       render 'new'
    end
  end

  def destroy
    Vaccine.find(params[:id]).destroy
    flash[:success] = "Vaccine deleted"
    redirect_back(fallback_location: vaccines_path )
  end

  def edit
    @vaccine = Vaccine.find(params[:id])
  end

  def update
    @vaccine = Vaccine.find(params[:id])
    if @vaccine.update_attributes(vaccine_params)
      flash[:success] = "Vaccine updated"
      redirect_to @vaccine
    else
      render 'edit'
    end
  end

private
  def vaccine_params
          params.require(:vaccine).permit(:name, :target, :route, :dose, :din, :notes)
  end

# Find vaccine by last name or health card number, depending on input format  
  def myfind (str)
        if str.match(/^[[:graph:]]+$/)                # name of the vaccine
          Vaccine.where("lower(name) like ?", "%#{str.downcase}%")
        end
  end
  
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
end

app/views/vaccines/_form.html.erb
<%= form_for @vaccine do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label 'Name' %>
  <%= f.text_field :name %>

  <%= f.label 'Target' %>
  <%= f.text_field :target %>

  <%= f.label 'Route' %>
  <%= f.text_field :route %>
  
  <%= f.label 'Dose' %>
  <%= f.text_field :dose %>
  
  <%= f.label 'DIN' %>
  <%= f.text_field :din %>
  
  <%= f.text_area :notes, rows:4, placeholder: 'Notes' %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

app/views/vaccines/_vaccine.html.erb
     <tr>
	<td><%= link_to vaccine.name, vaccine %> </td>
	<td><%= vaccine.target %> </td> 
	<td><%= vaccine.route %></td> 
	<td><%= vaccine.dose %></td> 
	<td><%= vaccine.din %></td> 
	<td><%= vaccine.notes %></td> 
  	<% if current_user.admin?  %>
		<td> <%= link_to "delete", vaccine, method: :delete, data: { confirm: "Are you sure you want to delete #{vaccine.name}?" } %> </td>
	<% end %>
     </tr>

app/views/vaccines/create.html.erb
<h1>Vaccines#create</h1>
<p>Find me in app/views/vaccines/create.html.erb</p>

app/views/vaccines/destroy.html.erb
<h1>Vaccines#destroy</h1>
<p>Find me in app/views/vaccines/destroy.html.erb</p>

app/views/vaccines/edit.html.erb
<% provide(:title, 'Edit Vaccine') %>
<% provide(:button_text, 'Save changes') %>
<h1>Edit Vaccine</h1>

<div class="row justify-content-md-center">
  <div class="col-md-4 col-md-offset-4">

<%= render 'form' %>

  </div>
</div>

app/views/vaccines/index.html.erb
<% provide(:title, 'All Vaccines') %>

<table class="tbl table-hover" >
  <thead>
      <tr>
          <th class="tbl_md">Name</th>
          <th class="tbl_md">Target</th>
          <th>Route</th>
	  <th>Dose</th>
	  <th>DIN</th>
	  <th>Notes</th>
	  <% if  current_user.admin? %>
	     <th></th>
     	  <% end %>
      </tr>
  </thead>
  <tbody>

  <%= render @vaccines %>

  </tbody>
</table>

<div class="bottom_buttons ">
<%= will_paginate @vaccines, class: "btn" %>
<% if current_user.admin?  %>
<%= button_to "Add New Vaccine", new_vaccine_path, class: "btn btn-primary col-md-12", :method => "get" %>
<% end %>
</div>

app/views/vaccines/new.html.erb
<% provide(:title, 'New Vaccine') %>
<% provide(:button_text, 'Save') %>
<h1>New Vaccine </h1>

<div class="row justify-content-sm-center">
	<div class="col-sm-4 col-sm-offset-4">

	<%= render 'form' %>

	</div>
</div>

app/views/vaccines/show.html.erb
<% provide(:title, @vaccine.name) %>

	<h1>Vaccine:  <%= @vaccine.name %> - details  </h1>

<div class="row justify-content-sm-center">
  <div class="col-sm-6 col-sm-offset-3">
	   <pre>
	        Name:       <%= @vaccine.name %>
	        Target:   <%= @vaccine.target %>
	        Route:       <%= @vaccine.route %>
	        Dose:       <%= @vaccine.dose %>
	        DIN:       <%= @vaccine.din %>
	        Notes:        <%= @vaccine.notes %>
           </pre>

    <%= button_to "Edit", edit_vaccine_path(@vaccine), class: "btn btn-primary", :method => "get" %>

  </div>
</div>