config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/ra_messages/index(/:id)' => 'claims#find', constraints: { query_string: /findstr/ }
  get 'ra_messages/index'
  
  get '/forms/index(/:id)' => 'forms#find', constraints: { query_string: /findstr/ }
  get '/forms/index'

  get '/claims/index(/:id)' => 'claims#find', constraints: { query_string: /findstr/ }
  get '/claims/index' 
  get '/daily_charts/index' => 'daily_charts#find', constraints: { query_string: /findstr/ }
  get '/daily_charts/index'
  get '/drugs/index' => 'drugs#find', constraints: { query_string: /findstr/ }
  get '/drugs/index' 
  get '/providers/index' => 'providers#find', constraints: { query_string: /findstr/ }
  get '/providers/index' 
  get '/reports/index' => 'reports#find', constraints: { query_string: /findstr/ }
  get '/reports/index' 
  get '/procedures/index' => 'procedures#find', constraints: { query_string: /findstr/ }
  get '/procedures/index' 
  get '/diagnoses/index' => 'diagnoses#find', constraints: { query_string: /findstr/ }
  get '/diagnoses/index' 
  get '/doctors/index' => 'doctors#find', constraints: { query_string: /findstr/ }
  get '/doctors/index' 
 # post '/daysheet/index', to: 'sessions#set_doctor' 
  post '/set_doctor', to: 'sessions#set_doctor'
  get '/set_doctor', to: 'sessions#set_doctor' 
  get '/daysheet/index', to: 'daysheet#index', as: :daysheet
  get '/vaccines/index', to:  "vaccines#find", constraints: { query_string: /findstr/ }
  get '/vaccines/index' 
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/news', to: 'static_pages#news'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/patients(/:id)', to: 'patients#find', constraints: { query_string: /findstr/ }
  post  '/patients(/:id)/card', to: 'patients#card'
  get '/patients(/:id)/card', to: 'patients#card'
  #get '/daysheet/card', to: 'patients#card'
  #post  '/daysheet/card', to: 'patients#card'

  get  '/patsignup', to: 'patients#new'
  post '/patsignup', to: 'patients#create'

  get '/visits' => 'visits#daysheet', constraints: { query_string: /date/ }
  get '/visits' => 'visits#index'
  get '/billings' => 'billings#index'
  post '/billings/export_csv', to: 'billings#export_csv'
  post '/billings/export_edt', to: 'billings#export_edt'
  post '/billings/export_cabmd', to: 'billings#export_cabmd'
  get "/procedures/get_by_code", to: "procedures#get_by_code" 
  
  
  resources :users
  resources :patients do
    get 'label', on: :member
    get 'addrlabel', on: :member
    get 'chart', on: :member
    resources :invoices do
      get 'invoice', on: :member
    end
    resources :visits do  # , shallow: true         #, only: [:show, :create, :destroy, :new, :index]
      get 'visitform', on: :member
      get 'receipt', on: :member
      get 'referralform', on: :member
      get 'sendclaim', on: :member
      resources :documents
    end
  end
  
  resources :ra_messages, :ra_accounts, :ra_errcodes, :doctors, :diagnoses, :procedures, :providers, 
	    :drugs, :invoices, :vaccines, :daily_charts, :export_files, :edt_files, :forms

  resources :claims do
    resources :services
  end
  resources :reports do
     get 'export', on: :member
     get 'download', on: :member
  end
  resources :paystubs do
     get 'export', on: :member
     get 'download', on: :member
  end
  get 'budget', to: 'paystubs#budget'

# resources :billings     # historical billing table - not used
  
end

app/models/procedure.rb
class Procedure < ApplicationRecord
        default_scope -> {order(code: :asc)}
        
	attr_accessor :full_name, :age, :cardstr #, :prov_fee_real, :spec_fee_real, :ana_fee_real, :non_ana_fee_real

	VALID_PCODE_REGEX = /\A[a-z]\d{3}[a-z]\z/i
	validates :code, presence: true, length: { maximum: 10 }, uniqueness: { case_sensitive: false }
	validates :code, format: { with: VALID_PCODE_REGEX, message: "for HCP procedure can only be in format <letter><3_digit_number><letter>" }, if: Proc.new { |a| (a.ptype == 1)}
	validates :ptype, presence: true, length: { maximum: 5 }
	validates :descr, length: { maximum: 100 }, presence: true
	validates :cost, presence: true, numericality: true #{greater_than_or_equal_to: 0} 
	validates :unit, presence: true, inclusion: { in: 0..20 }
	validates :fac_req, inclusion: { in: [true, false] }, allow_blank: true
	validates :adm_req, inclusion: { in: [true, false] }, allow_blank: true
	validates :diag_req, inclusion: { in: [true, false] }, allow_blank: true
	validates :ref_req, inclusion: { in: [true, false] }, allow_blank: true
	validates :percent, numericality: true, allow_blank: true 

	before_validation { code.upcase! rescue nil }
	before_validation { code.strip! rescue nil }
	
	before_save { self.prov_fee = (cost*100).to_i  }
	
def prov_fee_real
  sprintf '%.2f', prov_fee/100.0
end

def spec_fee_real
  sprintf '%.2f', spec_fee/100.0
end

def ass_fee_real
  sprintf '%.2f', ass_fee/100.0
end

def ana_fee_real
  sprintf '%.2f', ana_fee/100.0
end

def non_ana_fee_real
  sprintf '%.2f', non_ana_fee/100.0
end

def insured?
  ptype == 1 
end

def cash?
  ptype == 2
end

end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
	helper_method :sort_column, :sort_direction

        before_action :logged_in_user #, only: [:index, :edit, :update]
        before_action :admin_user, only: :destroy

  def index
     @procedures = Procedure.reorder(sort_column + ' ' + sort_direction).paginate(page: params[:page]) #, per_page: 40)
     flash.now[:info] = "Showing All Procedures"
  end

  def find
      str = params[:findstr].strip
      @procedures = myfind(str.upcase)
      if @procedures.any?
         @procedures = @procedures.paginate(page: params[:page])
         flash.now[:info] = "Found: #{@procedures.count} procedures"
         render 'index'
      else
	 flash.now[:warning] = "Procedure not found #{str.inspect} - #{view_context.link_to('Add New?', new_procedure_path)} ".html_safe
	 render  inline: '', layout: true
#	 redirect_to procedures_path 
      end
  end

# Called by JS in visit _form  
  def get_by_code
    code = params[:code]
    proc = Procedure.find_by(code: code).as_json
    respond_to do |format|
        format.json {
            render json: proc
        }
    end
  end

  def show
    @procedure = Procedure.find(params[:id])
  end

  def new
    @procedure = Procedure.new
  end

  def create
    @procedure = Procedure.new(procedure_params)
    if @procedure.save
       flash[:success] = "Procedure created"
       redirect_to procedures_path
    else
       render 'new'
    end
  end

  def destroy
    Procedure.find(params[:id]).destroy
    flash[:success] = "Procedure deleted"
    redirect_to procedures_url
  end

   def edit
    @procedure = Procedure.find(params[:id])
  end

  def update
    @procedure = Procedure.find(params[:id])
    if @procedure.update_attributes(procedure_params)
      flash[:success] = "Procedure updated"
      redirect_to procedures_url 
    else
      render 'edit'
    end
  end

private
  def procedure_params
          params.require(:procedure).permit(:code, :qcode, :ptype, :descr, :cost, :prov_fee, :ass_fee, :spec_fee, :ana_fee, :non_ana_fee,
					    :unit, :fac_req, :adm_req, :diag_req, :ref_req, :percent, :eff_date, :term_date, :active)
  end

# Find procedure by code/description
  def myfind (str)
	if str.match(/^\w[[:digit:]]{,3}\w$/)
          Procedure.where("code like ?", "%#{str}%")  
        elsif str.match(/^[[:graph:]]+$/)
		Procedure.where("upper(descr) like ? OR upper(code) like ?", "%#{str.upcase}%", "%#{str.upcase}%" )
        else
          []
        end
  end

  def sort_column
      Procedure.column_names.include?(params[:sort]) ? params[:sort] : "code"
  end

  def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end


end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= form_for @procedure do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <!-- Row 1 -->
<div class="row">
  <div class="col-sm-2">
	  <%= f.label :Code %>
          <%= f.text_field :code %>
  </div>
  
  <div class="col-sm-2">
	  <%= f.label :type %>
          <%= f.select :ptype, PROC_TYPES %>
  </div>

  <div class="col-sm-2">
	  <%= f.label :units %>
	  <%= f.text_field :unit, value: @procedure.unit || 1 %>
  </div>

  <div class="col-sm-2">
	  <%= f.label :percent %>
	  <%= f.text_field :percent, value: @procedure.percent || 0 %>
  </div>
</div>

  <!-- Row 2 -->
<div class="row">
  <div class="col-sm-8">
	  <%= f.label :description %>
	  <%= f.text_field :descr %>
  </div>
</div>

  <!-- Row 3 -->

<div class="row">
  <div class="col-sm-2">
          <%= f.label :provider_fee %>
          <%= f.text_field :cost %>
  </div>

  <div class="col-sm-2" style="display:none;">
          <%= f.label 'Specialist Fee' %>
          <%= f.text_field :spec_fee %>
  </div>

  <div class="col-sm-2" style="display:none;">
          <%= f.label 'Assistant Fee' %>
          <%= f.text_field :ass_fee %>
  </div>

  <div class="col-sm-2" style="display:none;">
          <%= f.label 'Anesth Fee' %>
          <%= f.text_field :ana_fee %>
  </div>
</div>

  <!-- Row 4 -->

<div class="row">
    <div class="col-sm-2">
          <%= f.label :'Effective Date' %>
          <%= f.date_field :eff_date %>
    </div>

    <div class="col-sm-2">
          <%= f.label :'Term Date' %>
          <%= f.date_field :term_date %>
    </div>
   
    <div class="col-sm-1">
    </div>

    <div class="col-sm-1" style="display:none;">
          <%= f.label :adm? %>
          <%= f.check_box :adm_req %>
    </div>

    <div class="col-sm-1">
          <%= f.label :'Requires Diagnosis?' %>
          <%= f.check_box :diag_req %>
    </div>

    <div class="col-sm-1">
          <%= f.label :'Requires Referral?' %>
          <%= f.check_box :ref_req %>
    </div>

    <div class="col-sm-1">
          <%= f.label :'Active procedure?' %>
          <%= f.check_box :active  %>
    </div>

</div>

  <!-- Row 5 -->

  <div style="height: 20px;"></div>
<div class="row">
    <div class="col-sm-8">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
</div>

<% end %>

app/views/procedures/_procedure.html.erb
     <tr>
	<td><%= link_to "#{procedure.code}", edit_procedure_path(procedure) %> </td>
	<td><%= procedure.ptype %> </td> 
	<td><%= procedure.descr %></td> 
	<td><%= procedure.cost %></td> 
	<td><%= procedure.unit %></td> 
	<td><%= procedure.diag_req %></td> 
	<td><%= procedure.ref_req %></td> 
	<td><%= procedure.eff_date %></td> 
	<td><%= procedure.active %></td> 
	<td>
	<% if current_user.admin?  %>
		<%= link_to "delete", procedure, method: :delete, data: { confirm: "Are you sure you want to delete procedure #{procedure.code}?" } %>
        <% end %>
	</td>
     </tr>

app/views/procedures/edit.html.erb
<% provide(:title, 'Edit procedure') %>
<% provide(:button_text, 'Save changes') %>
<h1>Edit procedure</h1>

<div class="col-md-9 col-sm-12 col-md-offset-3 col-sm-offset-2">
<%= render 'form' %>
</div>

app/views/procedures/index.html.erb
<% provide(:title, 'All procedures') %>

<table class="tbl table-hover" >
  <thead>
      <tr>
	  <th><%= sortable 'code', 'Svc Code' %></th>
	  <th><%= sortable 'ptype', :Type %></th>
	  <th class="tbl_lg"> <%= sortable 'descr', :Description %> </th>
	  <th>Provider Fee</th>
	  <th>Units</th>
	  <th>Diag required?</th>
	  <th>Ref. required?</th>
	  <th>Eff. Date</th>
	  <th><%= sortable 'active' %></th>
	  <th></th>
      </tr>
  </thead>
  <tbody>

  <%= render @procedures %>

  </tbody>
</table>

<div class="bottom_buttons ">
<%= will_paginate @procedures, class: "btn" %>
<%= button_to "Add Procedure", new_procedure_path, class: "btn btn-primary col-md-12", :method => "get" %>
</div>

app/views/procedures/new.html.erb
<% provide(:title, 'New Procedure') %>
<% provide(:button_text, 'Save') %>
<h1>New Procedure</h1>

<div class="col-md-8 col-sm-12 col-md-offset-3 col-sm-offset-3">
    <%= render 'form' %>
</div>

app/views/procedures/show.html.erb
<% provide(:title, @procedure.code) %>

	<h1>Procedure <%= @procedure.code %> - details  </h1>

<div class="row justify-content-md-center">
  <div class="col-md-6 col-md-offset-3">
	   <pre>

	      Code:         <%= @procedure.code %>
	      Type:         <%= @procedure.ptype %>
	      Description:  <%= @procedure.descr %>
	      Provider fee: $<%= @procedure.prov_fee_real rescue 0.00 %>
	      Specialist fee: $<%= @procedure.spec_fee_real rescue 0.00 %>
	      Assistant fee: $<%= @procedure.ass_fee_real  rescue 0.00 %>
	      Anesthesiologist fee: $<%= @procedure.ana_fee_real rescue 0.00 %>
	      Non-Anesthesiologist fee: $<%= @procedure.non_ana_fee_real rescue 0.00 %>
	      Unit: <%= @procedure.unit %>
	      Fac req?: <%= @procedure.fac_req %>
	      Adm req?: <%= @procedure.adm_req %>
	      Diag req?: <%= @procedure.diag_req %>
	      Ref req?: <%= @procedure.ref_req %>
	      Percent: <%= @procedure.percent %>
	      Effective date: <%= @procedure.eff_date %>
	      Termination date: <%= @procedure.term_date %>
	      Active?: <%= @procedure.active %>

           </pre>
    <%= button_to "Edit", edit_procedure_path(@procedure), class: "btn btn-primary", :method => "get" %>
    <p>
    <%= button_to "Back", procedures_path, class: "btn btn-primary", :method => "get" %>
  </div>
</div>