config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/ra_messages/index(/:id)' => 'claims#find', constraints: { query_string: /findstr/ }
  get 'ra_messages/index'
  
  get '/forms/index(/:id)' => 'forms#find', constraints: { query_string: /findstr/ }
  get '/forms/index'

  get '/claims/index(/:id)' => 'claims#find', constraints: { query_string: /findstr/ }
  get '/claims/index' 
  get '/daily_charts/index' => 'daily_charts#find', constraints: { query_string: /findstr/ }
  get '/daily_charts/index'
  get '/drugs/index' => 'drugs#find', constraints: { query_string: /findstr/ }
  get '/drugs/index' 
  get '/providers/index' => 'providers#find', constraints: { query_string: /findstr/ }
  get '/providers/index' 
  get '/reports/index' => 'reports#find', constraints: { query_string: /findstr/ }
  get '/reports/index' 
  get '/procedures/index' => 'procedures#find', constraints: { query_string: /findstr/ }
  get '/procedures/index' 
  get '/diagnoses/index' => 'diagnoses#find', constraints: { query_string: /findstr/ }
  get '/diagnoses/index' 
  get '/doctors/index' => 'doctors#find', constraints: { query_string: /findstr/ }
  get '/doctors/index' 
 # post '/daysheet/index', to: 'sessions#set_doctor' 
  post '/set_doctor', to: 'sessions#set_doctor'
  get '/set_doctor', to: 'sessions#set_doctor' 
  get '/daysheet/index', to: 'daysheet#index', as: :daysheet
  get '/vaccines/index', to:  "vaccines#find", constraints: { query_string: /findstr/ }
  get '/vaccines/index' 
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/news', to: 'static_pages#news'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/patients(/:id)', to: 'patients#find', constraints: { query_string: /findstr/ }
  post  '/patients(/:id)/card', to: 'patients#card'
  get '/patients(/:id)/card', to: 'patients#card'
  #get '/daysheet/card', to: 'patients#card'
  #post  '/daysheet/card', to: 'patients#card'

  get  '/patsignup', to: 'patients#new'
  post '/patsignup', to: 'patients#create'

  get '/visits' => 'visits#daysheet', constraints: { query_string: /date/ }
  get '/visits' => 'visits#index'
  get '/billings' => 'billings#index'
  post '/billings/export_csv', to: 'billings#export_csv'
  post '/billings/export_edt', to: 'billings#export_edt'
  post '/billings/export_cabmd', to: 'billings#export_cabmd'
  get "/procedures/get_by_code", to: "procedures#get_by_code" 
  
  
  resources :users
  resources :patients do
    get 'label', on: :member
    get 'addrlabel', on: :member
    get 'chart', on: :member
    resources :invoices do
      get 'invoice', on: :member
    end
    resources :visits do  # , shallow: true         #, only: [:show, :create, :destroy, :new, :index]
      get 'visitform', on: :member
      get 'receipt', on: :member
      get 'referralform', on: :member
      get 'sendclaim', on: :member
      resources :documents
    end
  end
  
  resources :ra_messages, :ra_accounts, :ra_errcodes, :doctors, :diagnoses, :procedures, :providers, 
	    :drugs, :invoices, :vaccines, :daily_charts, :export_files, :edt_files, :forms

  resources :claims do
    resources :services
  end
  resources :reports do
     get 'export', on: :member
     get 'download', on: :member
  end
  resources :paystubs do
     get 'export', on: :member
     get 'download', on: :member
  end
  get 'budget', to: 'paystubs#budget'

# resources :billings     # historical billing table - not used
  
end

app/models/report.rb
class Report < ApplicationRecord

	default_scope -> { order(id: :desc) }
	attr_accessor :doctor, :filespec

	validates :name, presence: true, length: { maximum: 30 }
	validates :rtype, presence: true, inclusion: { in: [SC_REPORT, PC_REPORT] } 
	validates :timeframe, numericality: { only_integer: true }, allow_blank: true
	validates :doc_id, numericality: { only_integer: true }, allow_blank: true
	validates :sdate, presence: true, if: Proc.new { |a| a.rtype == DAILY_REPORT || a.rtype == DRANGE_REPORT}
	validates :edate, presence: true, if: Proc.new { |a| a.rtype == DRANGE_REPORT}

  def doctor
	  Doctor.find(doc_id) if doc_id > 0
  end

  def filespec
    REPORTS_PATH.join(filename) rescue nil
  end

  def filesize 
    sprintf("%.2f", File.size(self.filespec).to_f/2**20) rescue 0
  end

  def timeframe_str
    REPORT_TFRAMES.invert[self.timeframe] rescue ''
  end

  def type_str 
    REPORT_TYPES.invert[self.rtype]
  end
  
end

app/controllers/reports_controller.rb
 class ReportsController < ApplicationController
        include My::Forms
	require 'fileutils'

	helper_method :sort_column, :sort_direction

	before_action :logged_in_user #, only: [:index, :edit, :update]
	before_action :admin_user, only: :destroy

  def index
    store_location

    @reports = Report.reorder(sort_column + ' ' + sort_direction).paginate(page: params[:page])
    flash.now[:info] = "Showing all reports (#{@reports.count})"
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    year = params[:date][:year]
    month  = params[:date][:month]
    prefix = @report.rtype + '_'
    prefix += @report.doc_id.to_s || 'all'
    sdate = @report.sdate.to_date rescue Date.today
    @doc  = Doctor.find(@report.doc_id)
    @report.name = "#{prefix}_#{sdate.strftime("%Y%m%d")}_#{@report.timeframe}"
    @report.filename = @report.name+'.pdf'
    @visits_that_day = []

# We will replace existing reports

    old_report = Report.find_by(filename: @report.filename)
    if old_report.present?
      File.delete( old_report.filespec ) rescue nil
      old_report.destroy
    end

    case @report.timeframe
       	when 1   # date
		 @report.sdate = sdate
		 @report.edate = sdate + 24.hours 
    		 @visits_that_day = Visit.where("date(entry_ts)=? and doc_id=?", @report.sdate, @report.doc_id)
    		 if @visits_that_day.any?
                   unbilled = @visits_that_day.where("status=?", ARRIVED)
		   flash[:danger] = "Cannot create report before billing is finished. There are still #{unbilled.count} visits marked as ARRIVED in Day Sheet for doctor #{@doc.lname}" if unbilled.any?
		 else
	            flash[:danger] = "Dr. #{@doc.lname} didn't see any patients on #{@report.sdate}"
		 end
	when 2   # mon
    	 	 @report.sdate = Date.new(year.to_i,month.to_i) 
    	  	 @report.edate = sdate + 1.month - 1.day
	when 3   # year
    	  	 @report.sdate = Date.new(year.to_i) 
    	  	 @report.edate = sdate + 1.year - 1.day 
	when 4   # range
		 @report.sdate = @report.sdate.to_date
		 @report.edate = @report.edate.to_date + 24.hours
	when 5   # all time
	  	 @report.sdate = Date.new(1950,01,01)
	  	 @report.edate = sdate + 100.years
	when 6   # Billing cycle - payment report
		 @report.sdate = Date.new(year.to_i,month.to_i) rescue Date.new(Time.now.year,Time.now.month)
		 @report.edate = 1.month.since(@report.sdate)
	else     # invalid
   	 	 flash.now[:danger] = "Invalid report timeframe: #{@report.timeframe}"
	end
    
       if flash[:danger]
	  redirect_to reports_path
       elsif @report.save
          flash.now[:success] = "Report created : #{@report.name.inspect}"
	  redirect_to export_report_path(@report)
#	  redirect_to reports_path
       else
	  flash.now[:danger] = @report.errors.full_messages.to_sentence
          render 'new'
       end
  end

  def show
    @report = Report.find(params[:id]) 
    redirect_to reports_path unless @report

    respond_to do |format|
      format.html { 
        send_file(@report.filespec,
             filename: @report.filename,
             type: "application/pdf",
             disposition: :inline) rescue 'Report file is missing'
      }
      format.js 
    end

#   @visits, @total, @insured, @uninsured = get_visits( @report )
#   @visits = @visits.reorder(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 25)
  end

  def download
   @report = Report.find( params[:id] )

   if File.exists?(@report.filespec)
          send_file @report.filespec,
	     filename: @report.filename,
             type: "application/pdf",
             disposition: :attachment
   else
     flash.now[:danger] = "File #{@report.filename} was not found - regenerating" 
     redirect_to export_report_path(@report)
   end
  end

# Generate PDF version of the report, save in reports directory
  def export
    @report = Report.find(params[:id])
    if @report.rtype == SC_REPORT      # Submitted Claims Report
       @visits, @total, @insured, @uninsured = get_visits( @report )
       @pdf = build_sc_report( @report, @visits )
    elsif @report.rtype == PC_REPORT   # Paid Claims Report
       prov_no = @report.doctor.provider_no rescue 0
       @claims = Claim.joins(:services).where(provider_no: prov_no).where(date_paid: (@report.sdate..@report.edate)).reorder('').group('claims.id,services.svc_date').order('services.svc_date')
       @pdf = build_pc_report( @report, @claims )
    end

    @pdf.render_file @report.filespec
    redirect_to reports_path, alert: "New report created for Dr. #{@doc.lname}"
  end

  def destroy
    @report = Report.find(params[:id]).destroy
    if @report.present?
      File.delete( @report.filespec ) rescue nil
      @report.destroy
      flash[:success] = "Report deleted"
    end

    redirect_to reports_url, page: params[:page]
  end

  def find
      str = params[:findstr].strip
      @reports = myfind(str)
      if @reports.any?
         @reports = @reports.paginate(page: params[:page])
	 flash.now[:info] = "Found: #{@reports.count} #{'report'.pluralize(@reports.count)}"
      else
         @reports = Report.new
         @reports = Report.paginate(page: params[:page])
	 flash.now[:info] = "Report #{str.inspect} was not found"
      end
      render 'index'
  end

private
  def report_params
     params.require(:report).permit(:doc_id, :name, :rtype, :filespec, :sdate, :edate, :filename, :timeframe )
  end

  # Find report(s) by name or type, depending on input format
  def myfind (str)
        if str.match(/^[[:digit:]]$/)   	         # rtype
          Report.where(rtype: str)
        elsif str.match(/^[[:graph:]]+$/)                # name
	  doc = Doctor.where("lower(lname) like ? AND bills='t'", "%#{str.downcase}%")
	  doc_id = doc[0].id rescue 0
	  Report.where("doc_id = ?", doc_id) if !doc.nil?
        else
          []
        end
  end

  def get_visits (rep)
    insured = 0
    if rep.doc_id
	    visits = Visit.where(doc_id: rep.doc_id).where(entry_ts: (rep.sdate..rep.edate)).order(entry_ts: :asc)
	    total = Visit.where(doc_id: rep.doc_id).where(entry_ts: (rep.sdate..rep.edate)).sum("fee+fee2+fee3+fee4")
	    visits.each{|v| insured += v.total_insured_fees}
    else
	    visits = Visit.where(entry_ts: (rep.sdate..rep.edate)).order(entry_ts: :asc)
	    total = Visit.where(entry_ts: (rep.sdate..rep.edate)).sum("fee+fee2+fee3+fee4")
	    visits.each{|v| insured += v.total_insured_fees}
    end
    uninsured = total - insured
    return [visits, total, insured, uninsured]
     
  end


  def sort_column
          Report.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
          %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for @report do |f| %>
		
<%= render 'shared/error_messages', object: f.object %>
<%= render 'shared/modal', size: 'lg' %>

<%
        doc_id = current_doctor.id if current_doctor
        disabled = []
        disabled = [DAILY_REPORT..DRANGE_REPORT] if @report.rtype = PC_REPORT   # Paid Claims
%>
  
<!-- Row 1 -->
<div class="row">
<div class="col-sm-2 col-sm-offset-4" >
  <%= f.label "Select Doctor" %>
  <%= f.collection_select :doc_id, get_active_doctors, :id, :lname,  selected: @report.doc_id || doc_id %>
</div >
    
<div class="col-sm-2" >
  <%= f.label "Report Type" %>
  <%= f.select :rtype, REPORT_TYPES, prompt: 'Select Type', selected: SC_REPORT %>
</div>
</div>

<!-- Row 2 -->
<div class="row">
<div class="col-sm-2 col-sm-offset-4" >
  <%= f.label "Timeframe" %>
  <%= f.select :timeframe, REPORT_TFRAMES, prompt: 'Select Timeframe', selected: @report.timeframe || DAILY_REPORT, disabled: disabled %>
</div>
</div>

<!-- Row 3 -->
<div class="row">
<div class="col-sm-2 col-sm-offset-4" id="sdate" >
  <%= f.label "Select Date" %>
  <%= f.date_field :sdate, class: 'datepicker', value: Time.now.strftime('%Y-%m-%d') %>
</div>
</div>

<!-- Row 3 -->
<div class="row">
<div class="col-sm-2 col-sm-offset-4" id="edate" style="display:none;">
  <%= f.label "To" %>
  <%= f.date_field :edate, class: 'datepicker' %>
</div>
</div>

<!-- Row 2 -->
<div class="row">
<div class="col-sm-2 col-sm-offset-4" id="year" style="display:none;">
  <%= f.label "Year" %>
  <%= select_year Time.now, start_year: Time.now.year-10, end_year: Time.now.year %>
</div>
</div>

<!-- Row 3 -->
<div class="row">
<div class="col-sm-2 col-sm-offset-4" id="month" style="display:none;">
  <%= f.label "Month" %>
  <%= select_month Time.now  %>
</div>
</div>

<!-- Row 4 -->


<% remote = device_is_desktop? %>

<div class="row">
  <div class='spacer-20'></div>
  <div class="col-sm-4 col-sm-offset-4">
  <%= f.submit yield(:button_text),  remote: remote, 'data-toggle':  "modal", 'data-target': '#modal-window', class: "btn btn-primary clickable", method: 'get' %>
  </div>
</div>

<% end %>

<script>
$(document).ready(function () {

    $('#new_report select[name="report[timeframe]"]').change(function () {
	switch ( $('#new_report select[name="report[timeframe]"]').val() ) {
		case "1":              	// Daily
			$('#edate').hide();
			$('#sdate').show();
			$('#year').hide();
			$('#month').hide();
		  	break;
		case "2":		// Monthly
			$('#edate').hide();
			$('#sdate').hide();
			$('#year').show();
			$('#month').show();
			break;
		case "3":		// Yearly
			$('#sdate').hide();
    			$('#edate').hide();
			$('#year').show();
			$('#month').hide();
			break;
		case "4":		// Date Range
			$('#sdate').show();
		  	$('#edate').show();
			$('#year').hide();
			$('#month').hide();
			break;
		case "5":		// All Time (defunct)
    			$('#sdate').hide();
    			$('#edate').hide();
			$('#year').hide();
			$('#month').hide();
			break;
		case "6":		// Billing Cycle
    			$('#sdate').hide();
    			$('#edate').hide();
			$('#year').hide();
			$('#month').show();
			break;

		}
			
    });
});
	
var rtype = document.getElementById("report_rtype");
//  alert(rtype.value);
$(rtype).change(function () {
  var rt = document.getElementById('report_timeframe');
  var tframe = document.getElementById('report_timeframe').getElementsByTagName("option");
  if (rtype.value == 'PC') {
    	$('#sdate').hide();
    	$('#edate').hide();
	$('#year').hide();
	$('#month').show();
	$(rt).prop('selectedIndex',4);  
        tframe[0].disabled = true;
        tframe[1].disabled = true;
        tframe[2].disabled = true;
        tframe[3].disabled = true;
  } else {
	$('#edate').hide();
	$('#sdate').show();
	$('#year').hide();
	$('#month').hide();
	$(rt).prop('selectedIndex',0);  
        tframe[0].disabled = false;
        tframe[1].disabled = false;
        tframe[2].disabled = false;
        tframe[3].disabled = false;
  }  
});

</script>

app/views/reports/_report.html.erb
    <tr>
	<% if report.filespec.present? && File.exists?(report.filespec) %>
	  <td><%= link_to report.id, report_path(report), remote: device_is_desktop?, 'data-toggle':  "modal", 'data-target': '#modal-window' %></td>
	<% else %>
	  <td><%= report.id %></td>
	<% end %>  
	<td><%= report.doctor.lname rescue 'All' %> </td> 
	<td><%= report.name %> </td>
	<% if report.filespec.present? && File.exists?(report.filespec) %>
	  <td><%= link_to '<i class="glyphicon glyphicon-download"></i>'.html_safe, download_report_path(report)  %></td>
	  <td><%= report.filesize %> </td>
        <% else %> <!-- regenerate report -->
	  <td><%= link_to '<i class="glyphicon glyphicon-question-sign"></i>'.html_safe, download_report_path(report)  %></td>
	  <td></td>
  	<% end %>

	<td><%= report.type_str %></td>
	<td><%= report.timeframe_str %></td> 
	
	<td>
	<% if report.timeframe == DAILY_REPORT %>
		<%= "#{report.sdate}" %>
	<% else %>
	   <%= "#{report.sdate} - #{report.edate}" %>
	<% end %>
	</td>

	<td><%= report.created_at %></td>

  	<% if current_user.admin?  %>
	   <td> <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, report, method: :delete, data: { confirm: "Are you sure you want to delete #{report.name}?" } %> </td>
	<% end %>

     </tr>

app/views/reports/_show.html.erb
<%
   provide(:title, "Doctor's Report")
   @doctor = Doctor.find(@report.doc_id)
%>
 
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">&times;</button>
	<b class="modal-title" id="myModalLabel"><%= @doctor.lname %>: Claims Report for <%= @report.sdate %></b>
</div>
<div class="modal-body">
	<iframe id="myModal" src="/reports/<%= @report.filename %>" frameborder="0" width="100%" height="600px"></iframe>
</div>
<div class="modal-footer">
  <button class="btn btn-primary" class="close" data-dismiss="modal">Dismiss</button>
</div>

app/views/reports/_visit.html.erb
<% patient = Patient.find(visit.patient_id) %>
<% doctor = Doctor.find(visit.doc_id) %>
<% diagnosis = Diagnosis.find_by(code: visit.diag_code) %>
<tr>
	<td><%= visit.entry_ts.strftime("%d-%b-%Y %H:%M") %></td>
	<td><%= visit.id %></td>
	<td><%= patient.full_name %> </td>
	<td><%= patient.ohip_num_full %> </td>
	<td><%= visit.diag_code %></td>
	<td><%= visit.proc_codes %></td>
	<td><%= BILLING_TYPES.invert[visit.bil_type] %></td>
	<td><%= sprintf("%.2f",visit.total_fee) %></td>
	<td><%= visit.entry_by %></td>
	<td><%= visit.billing_ref %></td>

</tr>

app/views/reports/delete.html.erb
<h1>Reports#delete</h1>
<p>Find me in app/views/reports/delete.html.erb</p>

app/views/reports/index.html.erb
<% provide(:title, 'All Reports') %>

<%= render 'shared/modal' %>

<table class="tbl table-hover">  <!--table table-hover table-condensed" >  -->
  <thead>
      <tr>
	  <th class='tbl_sm'><%= sortable 'id', '#' %></th>
	  <th><%= sortable 'doc_id', 'Doctor' %></th>
          <th class='tbl_lmd'>Report</th>
          <th class='tbl_md'>Download</th>
	  <th class='tbl_md'>Size(M) </th>
	  <th><%= sortable 'rtype', 'Type' %></th>
          <th>Timeframe</th>
	  <th cless='tbl_llg'><%= sortable 'sdate', 'Date Range' %></th>
	  <th><%= sortable 'created_at', 'Created' %></th>
	   <% if current_user.admin?  %>
          <th class='tbl_sm'></th>
	  <% end %>
      </tr>
  </thead>
  <tbody>

  <%= render @reports %>

  </tbody>
</table>

<div class="bottom_buttons ">
<%= will_paginate @reports, class: "btn" %> 
<%= button_to "Create New Report", new_report_path, class: "btn btn-primary col-md-12 ", method: 'get'  %>
</div>

app/views/reports/new.html.erb
<% provide(:title, 'New Report') %>
<% provide(:button_text, "Generate Report") %>
<h1>Create Report</h1>

    <%= render 'form' %>

app/views/reports/show.html.erb
<% provide(:title, @report.name) %>

<p>
    <div class="col-md-11 col-md-offset-1">
	   <pre>
	      Report: <b><%= @report.name %> </b> 

	      Type:       <%= REPORT_TFRAMES.invert[@report.timeframe] %>
	      Doctor:     <%= @report.doctor.lname rescue 'All Active'%>
	      Date:	  <%= @report.sdate %>
              <% if @report.timeframe > DAILY_REPORT %>
	      End Date:   <%= @report.edate %>
	      <% end %>
	      Total claims:     <%= @visits.count %>

	      Total Amount: <b>$<%= @total.round(2) %></b> Insured: <b>$<%= @insured.round(2) %></b> Uninsured: <b>$<%= @uninsured.round(2) %></b>
           </pre>

<% if @visits.present? %>
<table class="tbl table-hover" > <!--class="table table-hover table-condensed" > -->
  <thead>
      <tr>
	  <th><%= sortable 'entry_ts', :Date %></th>
          <th>Visit Id</th>
	  <th>Patient</th>
          <th>OHIP#</th>
	  <th><%= sortable 'diag_code', :Diagnosis %></th>
          <th>Procedure(s)</th>
	  <th><%= sortable 'bil_type', 'Bill.Type' %></th>
          <th>Ttl. Fee</th>
	  <th><%= sortable 'status', :Status %></th>
          <th>Entry By</th>
      </tr>
  </thead>
  <tbody>
          <%= render partial: "visit", collection: @visits %>
  </tbody>
</table>
<% end %>

<%  remote = device_is_desktop? %>
<%= render 'shared/modal', size: 'lg' %>

<div class="bottom_buttons ">
    <%= will_paginate @visits, class: "btn" %>
    <% if @report.filespec.blank? %> 
       <%= button_to "Generate PDF", export_report_path, class: "btn btn-primary", :method => "get", formtarget: "Form" %>
    <% else %>
       <%# button_to "Show PDF", show_pdf_report_path(@report), remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window', class: "btn btn-primary clickable", :method => "get", formtarget: 'form' %>
    <% end %>
</div>

</div>

app/views/reports/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'show') %>");
$("#modal-window").modal();